name: Build bootc image

on:
  schedule:
    - cron: '0 0 */2 * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build image
        run: |
          podman build \
            --build-arg=BASE_IMAGE=ghcr.io/bazzirco/bazzirco-dx:latest \
            -t ghcr.io/${{ github.repository }}:latest \
            -f ./Containerfile .

      - name: Rechunk image
        uses: hhd-dev/rechunk@v0.8.1
        with:
          ref: ghcr.io/${{ github.repository }}:latest

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          podman push ghcr.io/${{ github.repository }}:latest
